import type { Metadata } from "next";

import { Geist, Geist_Mono, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import "../styles/_variables.scss";
import "../styles/split-layout.scss";
import Providers from "@/components/auth/Providers";
import UserMenu from "@/components/auth/UserMenu";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ibmPlexSans.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <header
              className="flex justify-between items-center px-4 py-3 border-b border-border bg-background text-foreground z-10 shrink-0"
            >
              <div className="flex items-center gap-6">
                <a href="/" style={{ fontWeight: 600, textDecoration: 'none', color: 'inherit' }}>Lesson Builder</a>

                <nav className="hidden md:flex items-center gap-4 text-sm font-medium">
                  <a href="/marketplace" className="hover:text-blue-600 transition-colors">Marketplace</a>
                  <a href="/study-planner" className="hover:text-blue-600 transition-colors">Study Planner</a>
                </nav>
              </div>

              <div className="flex items-center gap-4">
                <ModeToggle />
                <UserMenu />
              </div>
            </header>
            <main style={{ flex: 1, minHeight: 0, overflow: "hidden" }}>
              {children}
            </main>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
