import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../styles/_variables.scss";
import "../styles/split-layout.scss";
import Providers from "@/components/auth/Providers";
import UserMenu from "@/components/auth/UserMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "0.75rem 1rem", borderBottom: "1px solid var(--border-color, #e5e7eb)" }}>
            <div style={{ fontWeight: 600 }}>Lesson Builder</div>
            <UserMenu />
          </header>
          <Script id="theme-init" strategy="beforeInteractive">
            {`
              try {
                const stored = localStorage.getItem('theme');
                const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                const wantDark = stored ? stored === 'dark' : prefersDark;
                const root = document.documentElement;
                if (wantDark) root.classList.add('dark'); else root.classList.remove('dark');
              } catch {}
            `}
          </Script>
          {children}
        </Providers>
      </body>
    </html>
  );
}
